-- CREATING A TABLE FOR OUR DATA

CREATE TABLE arrests (
	COUNTY VARCHAR(50),
	OFFENSE VARCHAR(250),
	STATUTE VARCHAR(10),
	CITATION VARCHAR(50),
	year2015 INT,
	year2016 INT,
	year2017 INT,
	year2018 INT,
	year2019 INT
);

-- OUR TABLE HAS DATA FROM EVERY COUNTY IN TEXAS
-- BECAUSE WE ARE FOCUSING ON WILCO, A VIEW FOR WILCO ARRESTS WAS CREATED

CREATE VIEW wilco_arrests AS
SELECT * FROM arrests 
WHERE county = 'WILLIAMSON';

-- STREAMLINING VALUES TO MATCH CREATED 'VIOLENT OFFENSES' TABLE
UPDATE 
    arrests
SET
    offense = REPLACE(offense, 'AGG','AGGRAVATED');
	
UPDATE 
    arrests
SET
    offense = REPLACE(offense, 'ASSLT','ASSAULT');

UPDATE 
    arrests
SET
    offense = REPLACE(offense, 'CRIM','CRIMINAL');

-- CLEANING UP 'UNATHORIZED' OFFENSES
UPDATE 
    arrests
SET
    offense = REPLACE(offense, 'UNAUTH','UNAUTHORIZED');

  -- VIEWING THE DISTINCT/UNIQUE TYPES OF OFFENSES. (657) TOTAL

SELECT DISTINCT(offense)
FROM wilco_arrests;

-- VIEWING THE SUM OF TOTAL ARRESTS IN WILCO BY YEAR 
SELECT SUM(year2015) AS ARRESTS_2015, SUM(year2016) AS ARRESTS_2016, SUM(year2017) AS ARRESTS_2017, 
SUM(year2018) AS ARRESTS_2018, SUM(year2019) AS ARRESTS_2019
FROM wilco_arrests;

-- VIEWING THE INFORMATION ON MURDER/HOMICIDE ARRESTS 
SELECT * FROM wilco_arrests
WHERE offense LIKE '%MURDER%' 
OR offense LIKE '%HOMICIDE%';

-- VIEWING THE SUM OF MURDER/HOMICIDE ARRESTS IN WILCO BY YEAR (2015-2019)
SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019
FROM wilco_arrests
WHERE offense LIKE '%MURDER%'
OR offense LIKE '%HOMICIDE%';

-- CREATING A TABLE TO HOUSE VIOLENT OFFENSES
CREATE TABLE violent_offenses (
	CHARGES VARCHAR(250));

-- INSERTING VIOLENT OFFENESES AS DEFINED BY THE FBI
INSERT INTO violent_offenses (
	CHARGES)
VALUES 
('MURDER'), 
('HOMICIDE'),
('NON-NEGLIGENT MANSLAUGHTER'),
('MANSLAUGHTER'),
('FORCIBLE RAPE'),
('RAPE'),
('AGGRAVATED ROBBERY'),
('ROBBERY'),
('AGGRAVATED ASSAULT');

-- IT'S NOT POSSIBLE TO COMBINE IN AND LIKE WITHIN A QUERY, SO MULTIPLE LIKE STATEMENTS WERE COMBINED 
-- TABLE FORMAT: OFFENSE WITH NUMBER OF ARRESTS FOR OFFENSE. TABLE WAS REDUCED TO VIOLENT OFFENSES AND ARRESTS SUMMED BY YEAR
SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019 FROM (
SELECT * FROM wilco_arrests
WHERE offense LIKE '%MURDER%'
OR offense LIKE '%HOMICIDE%'
OR offense LIKE '%MANSLAUGHTER%'
OR offense LIKE '%RAPE%'
OR offense LIKE '%AGGRAVATED ROBBERY%'
OR offense LIKE '%AGGRAVATED ASSAULT%'
) AS arrests_violence;

-- VIEWING ALL INFO ON DWI RELATED ARRESTS IN WILCO
SELECT * FROM wilco_arrests
WHERE offense LIKE '%DRIVING WHILE INTOXICATED%'


-- VIEWING SUM OF DWI ARREST IN WILCO BY YEAR
SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019 
FROM wilco_arrests 
WHERE offense LIKE '%DRIVING WHILE INTOXICATED%';


/* SUMMING PROPERTY OFFENSES AS DEFINED BY THE FBI IN THE UCR INDEX. THE FBI UCR INDEX LISTS 
THE FOLLOWING OFFENSES AS PROPERTY CRIMES: BURGLARY, LARCENY-THEFT, MOTOTOR VEHICLE, AND ARSON. 
I'LL ADD GRAFFITI AND CRIMINAL MISCHIEF TO THE LIST
*/ 

SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019
FROM wilco_arrests
WHERE offense LIKE '%BURGLARY%'
OR offense LIKE '%LARCENY%'
OR offense LIKE '%THEFT%'
OR offense LIKE '%UNAUTHORIZED USE OF VEHICLE%'
OR offense LIKE '%UNAUTHORIZED USE OF MOTOR VEHICLE%'
OR offense LIKE '%CRIMINAL MISCHIEF%'
OR offense LIKE '%GRAFFITI%'
OR offense LIKE '%ARSON%'

-- QUERYING POCS/DEL OFFENSES EXCLUDING POM
SELECT SUM(year2015) AS ARRESTS_2015, SUM(year2016) AS ARRESTS_2016, SUM(year2017) AS ARRESTS_2017, 
SUM(year2018) AS ARRESTS_2018, SUM(year2019) AS ARRESTS_2019
FROM wilco_arrests
WHERE offense LIKE '%MAN DEL'
OR offense LIKE '%MAN/DEL%'
OR offense LIKE '%POSS CS%'
OR offense LIKE '%POSSESSION/DELIVERY%'
OR offense LIKE '%DEL MAR%'
OR offense LIKE '%DEL/OFFER DEL%'
OR offense LIKE '%POSSESS CONTR SUBST%'

-- QUERYING THE SUM OF POM CHARGES - VARYING CHARGE LEVELS
SELECT SUM(year2015) AS ARRESTS_2015, SUM(year2016) AS ARRESTS_2016, SUM(year2017) AS ARRESTS_2017, 
SUM(year2018) AS ARRESTS_2018, SUM(year2019) AS ARRESTS_2019
FROM wilco_arrests
WHERE offense LIKE '%POSS MAR%'


/* WE WILL NOW DUPLICATE THE QUERIES AND GET DATA FOR THE NEIGHBORING COUNTY OF TRAVIS
   AND TEXAS AS A WHOLE */

CREATE VIEW travis_arrests AS
SELECT * FROM arrests 
WHERE county = 'TRAVIS';

-- VIEWING THE SUM OF MURDER/HOMICIDE ARRESTS IN TRAVIS BY YEAR (2015-2019)
SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019
FROM travis_arrests
WHERE offense LIKE '%MURDER%'
OR offense LIKE '%HOMICIDE%';

-- TABLE FORMAT: OFFENSE WITH NUMBER OF ARRESTS FOR OFFENSE. TABLE WAS REDUCED TO VIOLENT OFFENSES AND ARRESTS SUMMED BY YEAR
SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019 FROM (
SELECT * FROM travis_arrests
WHERE offense LIKE '%MURDER%'
OR offense LIKE '%HOMICIDE%'
OR offense LIKE '%MANSLAUGHTER%'
OR offense LIKE '%RAPE%'
OR offense LIKE '%AGGRAVATED ROBBERY%'
OR offense LIKE '%AGGRAVATED ASSAULT%'
) AS arrests_violence;

-- VIEWING SUM OF DWI ARREST IN TRAVIS BY YEAR
SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019 
FROM travis_arrests 
WHERE offense LIKE '%DRIVING WHILE INTOXICATED%';

/* SUMMING PROPERTY OFFENSES AS DEFINED BY THE FBI IN THE UCR INDEX. THE FBI UCR INDEX LISTS 
THE FOLLOWING OFFENSES AS PROPERTY CRIMES: BURGLARY, LARCENY-THEFT, MOTOTOR VEHICLE, AND ARSON. 
I'LL ADD GRAFFITI AND CRIMINAL MISCHIEF TO THE LIST
*/ 

SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019
FROM travis_arrests
WHERE offense LIKE '%BURGLARY%'
OR offense LIKE '%LARCENY%'
OR offense LIKE '%THEFT%'
OR offense LIKE '%UNAUTHORIZED USE OF VEHICLE%'
OR offense LIKE '%UNAUTHORIZED USE OF MOTOR VEHICLE%'
OR offense LIKE '%CRIMINAL MISCHIEF%'
OR offense LIKE '%GRAFFITI%'
OR offense LIKE '%ARSON%'

-- QUERYING POCS/DEL OFFENSES EXCLUDING POM
SELECT SUM(year2015) AS ARRESTS_2015, SUM(year2016) AS ARRESTS_2016, SUM(year2017) AS ARRESTS_2017, 
SUM(year2018) AS ARRESTS_2018, SUM(year2019) AS ARRESTS_2019
FROM travis_arrests
WHERE offense LIKE '%MAN DEL'
OR offense LIKE '%MAN/DEL%'
OR offense LIKE '%POSS CS%'
OR offense LIKE '%POSSESSION/DELIVERY%'
OR offense LIKE '%DEL MAR%'
OR offense LIKE '%DEL/OFFER DEL%'
OR offense LIKE '%POSSESS CONTR SUBST%'

-- QUERYING THE SUM OF POM CHARGES - VARYING CHARGE LEVELS
SELECT SUM(year2015) AS ARRESTS_2015, SUM(year2016) AS ARRESTS_2016, SUM(year2017) AS ARRESTS_2017, 
SUM(year2018) AS ARRESTS_2018, SUM(year2019) AS ARRESTS_2019
FROM travis_arrests
WHERE offense LIKE '%POSS MAR%'

/* NOW WE WILL QUERY THE SAME RESULTS BUT FOR TEXAS AS A WHOLE */

-- VIEWING THE SUM OF TOTAL ARRESTS IN TEXAS BY YEAR 
SELECT SUM(year2015) AS ARRESTS_2015, SUM(year2016) AS ARRESTS_2016, SUM(year2017) AS ARRESTS_2017, 
SUM(year2018) AS ARRESTS_2018, SUM(year2019) AS ARRESTS_2019
FROM arrests;

-- VIEWING THE SUM OF MURDER/HOMICIDE ARRESTS IN TRAVIS BY YEAR (2015-2019)
SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019
FROM arrests 
WHERE offense LIKE '%MURDER%'
OR offense LIKE '%HOMICIDE%';

-- TABLE FORMAT: OFFENSE WITH NUMBER OF ARRESTS FOR OFFENSE. TABLE WAS REDUCED TO VIOLENT OFFENSES AND ARRESTS SUMMED BY YEAR
SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019 FROM (
SELECT * FROM arrests
WHERE offense LIKE '%MURDER%'
OR offense LIKE '%HOMICIDE%'
OR offense LIKE '%MANSLAUGHTER%'
OR offense LIKE '%RAPE%'
OR offense LIKE '%AGGRAVATED ROBBERY%'
OR offense LIKE '%AGGRAVATED ASSAULT%'
) AS arrests_violence;

-- VIEWING SUM OF DWI ARREST IN TEXAS BY YEAR
SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019 
FROM arrests 
WHERE offense LIKE '%DRIVING WHILE INTOXICATED%';

/* SUMMING PROPERTY OFFENSES AS DEFINED BY THE FBI IN THE UCR INDEX. THE FBI UCR INDEX LISTS 
THE FOLLOWING OFFENSES AS PROPERTY CRIMES: BURGLARY, LARCENY-THEFT, MOTOTOR VEHICLE, AND ARSON. 
I'LL ADD GRAFFITI AND CRIMINAL MISCHIEF TO THE LIST
*/ 

SELECT SUM(year2015) AS YEAR2015, SUM(year2016) AS YEAR2016, 
SUM(year2017) AS YEAR2017, SUM(year2018) AS YEAR2018, SUM(year2019) AS YEAR2019
FROM arrests
WHERE offense LIKE '%BURGLARY%'
OR offense LIKE '%LARCENY%'
OR offense LIKE '%THEFT%'
OR offense LIKE '%UNAUTHORIZED USE OF VEHICLE%'
OR offense LIKE '%UNAUTHORIZED USE OF MOTOR VEHICLE%'
OR offense LIKE '%CRIMINAL MISCHIEF%'
OR offense LIKE '%GRAFFITI%'
OR offense LIKE '%ARSON%'

-- QUERYING POCS/DEL OFFENSES EXCLUDING POM
SELECT SUM(year2015) AS ARRESTS_2015, SUM(year2016) AS ARRESTS_2016, SUM(year2017) AS ARRESTS_2017, 
SUM(year2018) AS ARRESTS_2018, SUM(year2019) AS ARRESTS_2019
FROM arrests
WHERE offense LIKE '%MAN DEL'
OR offense LIKE '%MAN/DEL%'
OR offense LIKE '%POSS CS%'
OR offense LIKE '%POSSESSION/DELIVERY%'
OR offense LIKE '%DEL MAR%'
OR offense LIKE '%DEL/OFFER DEL%'
OR offense LIKE '%POSSESS CONTR SUBST%'

-- QUERYING THE SUM OF POM CHARGES - VARYING CHARGE LEVELS
SELECT SUM(year2015) AS ARRESTS_2015, SUM(year2016) AS ARRESTS_2016, SUM(year2017) AS ARRESTS_2017, 
SUM(year2018) AS ARRESTS_2018, SUM(year2019) AS ARRESTS_2019
FROM arrests
WHERE offense LIKE '%POSS MAR%'
